FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase

    Mimic_Dance_102: # uncomment to enable
      id: 101
      type: Mimic
    Mimic_Gangnam_Style:
      id: 102
      type: Mimic

  Passive:
    transitions: 
      FixStand: up.on_pressed
    mode: [
      1,1,1,1,1,1,
      1,1,1,1,1,1,
      1,1,1,
      1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,
    ]
    kd: [
      3,3,3,3,3,3,
      3,3,3,3,3,3,
      3,3,3,
      3,3,3,3,3,3,3,  
      3,3,3,3,3,3,3,  
    ]
  FixStand:
    transitions: 
      Passive: down.on_pressed
      Velocity: right.on_pressed
    kp: [
      100., 100., 100., 150., 40., 40.,
      100., 100., 100., 150., 40., 40.,
      200,200,200,
      40,40,40,40,40,40,40,
      40,40,40,40,40,40,40,
    ]
    kd: [
      2,2,2,4,2,2,
      2,2,2,4,2,2,
      5,5,5,
      10,10,10,10,10,10,10,
      10,10,10,10,10,10,10,
    ]
    ts: [0, 3]
    qs: [
      [],
      [ -0.1, 0,0,0.3,-0.2,0,
        -0.1, 0,0,0.3,-0.2,0,
        0,0,0,
        0, 0.25,0,0.97,0.15, 0,0,
        0, -0.25,0,0.97,-0.15, 0,0
      ]
    ]
  Velocity:
    transitions: 
      Passive: down.on_pressed
      Mimic_Dance_102: right.on_pressed
      Mimic_Gangnam_Style: left.on_pressed

    policy_dir: config/policy/velocity
    # policy_dir: ../../../logs/rsl_rl/unitree_g1_29dof_velocity
  Mimic_Dance_102:
    transitions: 
      Passive: down.on_pressed
      Velocity: right.on_pressed
    fps: 60
    motion_file: config/policy/mimic/dance_102/params/G1_Take_102.bvh_60hz.csv
    policy_dir: config/policy/mimic/dance_102/
    time_start: 2.8
    time_end: 24.0
  Mimic_Gangnam_Style:
    transitions: 
      Passive: down.on_pressed
      Velocity: right.on_pressed
    fps: 60
    motion_file: config/policy/mimic/gangnam_style/params/G1_gangnam_style_V01.bvh_60hz.csv
    policy_dir: config/policy/mimic/gangnam_style/
    time_start: 5.2
    time_end: 25.5

